[package]
name = "gflags-rs"
version = "0.1.0"
authors = ["Jeremy Fitzhardinge <jeremy@goop.org>"]
build = "build.rs"

[dependencies]
lazy_static = "1.0"

[build-dependencies]
bindgen = "0.37"
gcc = "0.3"
pkg-config = "0.3"